# Generated by Django 5.1.6 on 2025-02-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnsBigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PnsCombi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price_info', models.CharField(blank=True, max_length=100, null=True)),
                ('oneshot_price', models.IntegerField()),
                ('oneshot_info', models.CharField(blank=True, max_length=100, null=True)),
                ('m_charge_info', models.CharField(blank=True, max_length=100, null=True)),
                ('i_charge_info', models.CharField(blank=True, max_length=100, null=True)),
                ('t_charge_info', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('charge_info', models.CharField(blank=True, max_length=100, null=True)),
                ('bigo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PnsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('jisa', models.CharField(max_length=50)),
                ('agency_name', models.CharField(max_length=100)),
                ('link_url', models.CharField(max_length=255)),
                ('kc_manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kc_manager_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('kt_manager_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('kt_manager_phone1', models.CharField(blank=True, max_length=100, null=True)),
                ('kt_manager_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('kt_manager_phone2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PnsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price_info', models.CharField(blank=True, max_length=100, null=True)),
                ('oneshot_price', models.IntegerField()),
                ('oneshot_info', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('charge_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
