# Generated by Django 5.1.6 on 2025-02-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pnsbigo_pnscombi_pnsmanager_pnsmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pnsbigo',
            table='pns_bigo',
        ),
        migrations.AlterModelTable(
            name='pnscombi',
            table='pns_combi',
        ),
        migrations.AlterModelTable(
            name='pnsmanager',
            table='pns_manager',
        ),
        migrations.AlterModelTable(
            name='pnsmodel',
            table='pns_model',
        ),
    ]
