# Generated by Django 5.1.6 on 2025-02-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pnsbigo_table_alter_pnscombi_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnsbigo',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
