# Generated by Django 5.1.6 on 2025-02-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pnsbigo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnsbigo',
            name='content',
            field=models.TextField(),
        ),
    ]
