# Generated by Django 5.1.6 on 2025-02-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_pnsbigo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnsmodel',
            name='type1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
