# Generated by Django 5.1.6 on 2025-02-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pnsmodel_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnscombi',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
