# Generated by Django 5.1.6 on 2025-02-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_pnscombi_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnsbigo',
            name='de',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='pnscombi',
            name='de',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='pnsmanager',
            name='de',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='pnsmodel',
            name='de',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
